# Generated by Django 4.2.7 on 2024-05-02 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_purchased_quantity', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_drugs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_issued_to', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True)),
                ('siv', models.CharField(blank=True, max_length=100, null=True)),
                ('srv', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, null=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='store.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='store.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'drugs issued record',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.drug')),
            ],
            options={
                'verbose_name_plural': 'purchases record',
            },
        ),
    ]
