# Generated by Django 4.2.7 on 2024-07-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'restocking record'},
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pack_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_categories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ANALGESICS', 'Analgesics'), ('ANESTHETICS', 'Anesthetics'), ('ANTIBIOTICS', 'Antibiotics'), ('ANTICOAGULANTS', 'Anticoagulants'), ('ANTICONVULSANTS', 'Anticonvulsants'), ('ANTIDEPRESSANTS', 'Antidepressants'), ('ANTIDIABETICS', 'Antidiabetics'), ('ANTIEMETICS', 'Antiemetics'), ('ANTIFUNGALS', 'Antifungals'), ('ANTIHISTAMINES', 'Antihistamines'), ('ANTIHYPERTENSIVES', 'Antihypertensives'), ('ANTI_INFLAMMATORIES', 'Anti-inflammatories'), ('ANTINEOPLASTICS', 'Antineoplastics'), ('ANTIPARASITICS', 'Antiparasitics'), ('ANTIPSYCHOTICS', 'Antipsychotics'), ('ANTIVIRALS', 'Antivirals'), ('BRONCHODILATORS', 'Bronchodilators'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS_STIMULANTS', 'CNS Stimulants'), ('CORTICOSTEROIDS', 'Corticosteroids'), ('DERMATOLOGICALS', 'Dermatologicals'), ('DIURETICS', 'Diuretics'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('HORMONES', 'Hormones'), ('IMMUNOSUPPRESSANTS', 'Immunosuppressants'), ('LIPID_LOWERING', 'Lipid-lowering'), ('MUSCLE_RELAXANTS', 'Muscle Relaxants'), ('NSAIDS', 'NSAIDs'), ('OPIOIDS', 'Opioids'), ('OPHTHALMICS', 'Ophthalmics'), ('PSYCHOTROPICS', 'Psychotropics'), ('SEDATIVES_HYPNOTICS', 'Sedatives/Hypnotics'), ('THYROID_PREPARATIONS', 'Thyroid Preparations'), ('VACCINES', 'Vaccines'), ('VITAMINS_MINERALS', 'Vitamins and Minerals'), ('OTHER', 'Other')], max_length=200, verbose_name='CLASS OF DRUG'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BRAND NAME'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='COST PRICE'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='DATE DRUG WAS ADDED'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DOSAGE FORM'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='DATE ADDED'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GENERIC NAME'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='DRUG NAME'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='pack_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PACK SIZE'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SUPPLIER'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='total_purchased_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='TOTAL QTY PURCHASED'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='DATE UPDATED'),
        ),
        migrations.AlterField(
            model_name='record',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CURRENT BALANCE'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(auto_now_add=True, verbose_name='DATE DRUG WAS ISSUED'),
        ),
        migrations.AlterField(
            model_name='record',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER'),
        ),
        migrations.AlterField(
            model_name='record',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY ISSUED'),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='REMARKS'),
        ),
        migrations.AlterField(
            model_name='record',
            name='siv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SIV'),
        ),
        migrations.AlterField(
            model_name='record',
            name='srv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SRV'),
        ),
        migrations.AlterField(
            model_name='record',
            name='unit_issued_to',
            field=models.CharField(blank=True, choices=[('A & E', 'A & E'), ('IN-PATIENT', 'IN-PATIENT'), ('NHIS', 'NHIS'), ('SPINE', 'SPINE'), ('SOPD', 'SOPD'), ('THEATRE', 'THEATRE')], max_length=100, null=True, verbose_name='PHARMACY UNIT ISSUED TO'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED'),
        ),
    ]
