# Generated by Django 4.2.7 on 2025-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitissuerecord',
            name='moved_to',
            field=models.CharField(blank=True, choices=[('expiry', 'Expiry'), ('damage', 'Damage'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Box',
        ),
    ]
