# Generated by Django 4.2.7 on 2024-07-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_purchase_options_remove_drug_pack_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='supply_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='REMARKS'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='unit_issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.unit'),
        ),
    ]
