# Generated by Django 4.2.7 on 2025-01-10 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_unitissuerecord_moved_to_delete_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_drug_category', to='store.category')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.drug')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_drug', to='store.unit')),
            ],
        ),
    ]
