# Generated by Django 4.2.7 on 2024-07-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_unit_drug_supply_date_alter_drug_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restock_category', to='store.category')),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.drug')),
            ],
            options={
                'verbose_name_plural': 'restocking record',
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
