# Generated by Django 4.2.7 on 2024-07-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_restock_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='restocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_restocking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('POWDER', 'POWDER'), ('GRANULE', 'GRANULE'), ('PELLET', 'PELLET'), ('SOLUTION', 'SOLUTION'), ('INFUSION', 'INFUSION'), ('SUSPENSIONS', 'SUSPENSION'), ('EMULSION', 'EMULSION'), ('TINCTURE', 'TINCTURE'), ('OINTMENT', 'OINMENT'), ('CREAM', 'CREAM'), ('GEL', 'GEL'), ('SUPPOSITORY', 'SUPPOSITORY'), ('INHALER', 'INHALER'), ('IMPLANT', 'IMPLANT'), ('LOZENGE', 'LOZENGEN'), ('SPRAY', 'SPRAY'), ('TRANSDERMAL PATCH', 'TRANSDERMAL PATCH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='supply_date',
            field=models.DateField(null=True),
        ),
    ]
