# Generated by Django 4.2.7 on 2025-01-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_drugrequest_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='drugrequest',
            name='drugs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
