# Generated by Django 4.2.7 on 2024-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_record_balance_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ANALGESIC', 'Analgesic'), ('ANAESTHETIC', 'Anaesthetic'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTICOAGULANT', 'Anticoagulant'), ('ANTICONVULSANT', 'Anticonvulsant'), ('ANTIDEPRESSANT', 'Antidepressant'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIDIARHEAL', 'Antidiarheal'), ('ANTIEMETIC', 'Antiemetic'), ('ANTIFUNGAL', 'Antifungal'), ('ANTIFIBRINOLYTICS', 'Antifibrinolytics'), ('ANTI_ACNE', 'Anti-Acne'), ('ANTIHISTAMINE', 'Antihistamine'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTI-INFLAMMATORY', 'Anti-inflammatory'), ('ANTINEOPLASTIC', 'Antineoplastic'), ('ANTIPARASITIC', 'Antiparasitic'), ('ANTIPSYCHOTIC', 'Antipsychotic'), ('ANTI-TUBERCULOSIS', 'Anti-Tuberculosis'), ('ANTI-UCLER', 'Anti-ulcer'), ('ANTIVIRAL', 'Antiviral'), ('BRONCHODILATOR', 'Bronchodilator'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS_STIMULANT', 'CNS Stimulant'), ('CORTICOSTEROID', 'Corticosteroid'), ('DERMATOLOGICAL', 'Dermatological'), ('DIURETIC', 'Diuretic'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('HORMONE', 'Hormone'), ('IMMUNOSUPPRESSANT', 'Immunosuppressant'), ('LIPID_LOWERING', 'Lipid-lowering'), ('MUSCLE_RELAXANT', 'Muscle Relaxant'), ('NSAID', 'NSAID'), ('OPIOID', 'Opioid'), ('OPHTHALMIC', 'Ophthalmic'), ('PSYCHOTROPIC', 'Psychotropic'), ('SEDATIVES_HYPNOTIC', 'Sedatives/Hypnotic'), ('THYROID_PREPARATION', 'Thyroid Preparation'), ('VACCINE', 'Vaccine'), ('VITAMINS_MINERAL', 'Vitamins and Mineral'), ('OTHER', 'Other')], max_length=200, verbose_name='CLASS OF DRUG'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('INJECTION', 'INJECTION'), ('INFUSION', 'INFUSION'), ('SUSPENSION', 'SUSPENSION'), ('SOLUTION', 'SOLUTION'), ('CONSUMABLE', 'CONSUMABLE'), ('POWDER', 'POWDER'), ('GRANULE', 'GRANULE'), ('PELLET', 'PELLET'), ('EMULSION', 'EMULSION'), ('TINCTURE', 'TINCTURE'), ('OINTMENT', 'OINMENT'), ('CREAM', 'CREAM'), ('GEL', 'GEL'), ('SUPPOSITORY', 'SUPPOSITORY'), ('INHALER', 'INHALER'), ('IMPLANT', 'IMPLANT'), ('LOZENGE', 'LOZENGEN'), ('SPRAY', 'SPRAY'), ('TRANSDERMAL PATCH', 'TRANSDERMAL PATCH')], max_length=100, null=True),
        ),
    ]
