# Generated by Django 4.2.7 on 2025-01-11 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_returneddrugs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitissuerecord',
            name='issued_to',
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='request_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('date_issued', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_category', to='store.category')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_drugs', to='store.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_unit', to='store.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_unit', to='store.unit')),
            ],
        ),
    ]
