# Generated by Django 4.2.7 on 2024-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_name_alter_drug_dosage_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='STRENGTH'),
        ),
        migrations.AddField(
            model_name='drug',
            name='trade_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TRADE NAME'),
        ),
    ]
