# Generated by Django 4.2.7 on 2024-08-15 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('store', '0008_remove_drug_brand_name_remove_drug_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_type', models.CharField(choices=[('MAIN_TO_LOCAL', 'Main Store to Local Store'), ('LOCAL_TO_LOCAL', 'Local Store to Local Store'), ('LOCAL_TO_DISPENSARY', 'Local Store to Dispensary Locker')], max_length=20)),
                ('siv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SIV')),
                ('srv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SRV')),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER')),
                ('quantity', models.PositiveIntegerField(verbose_name='QTY ISSUED')),
                ('date_issued', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='REMARKS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='store.category')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='store.drug')),
            ],
            options={
                'verbose_name_plural': 'drug distributions',
            },
        ),
        migrations.CreateModel(
            name='UnitStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True, verbose_name='Quantity Available')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_store_drugs', to='store.drug')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='update',
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='auth.group'),
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_units', to='store.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('MAIN', 'Main Store'), ('LOCAL', 'Local Store'), ('DISPENSARY', 'Dispensary Locker')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='unitstore',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_store', to='store.unit'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_from', to='store.unit'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribution',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions_to', to='store.unit'),
        ),
    ]
