# Generated by Django 4.2.7 on 2025-01-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_patient_alter_dispenserecord_patient_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugrequest',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_drug', to='store.unit'),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
