# Generated by Django 4.2.7 on 2024-08-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_distribution_unitstore_remove_unit_update_unit_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SIV')),
                ('srv', models.CharField(blank=True, max_length=100, null=True, verbose_name='SRV')),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='INVOICE NUMBER')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='QTY ISSUED')),
                ('date_issued', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='REMARKS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='store.category')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to='store.drug')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'drugs issued record',
            },
        ),
        migrations.RemoveField(
            model_name='unitstore',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='unitstore',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='group',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='unit',
            name='update',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='UnitStore',
        ),
        migrations.AddField(
            model_name='record',
            name='unit_issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.unit'),
        ),
    ]
