# Generated by Django 4.2.7 on 2025-01-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_drugrequest_unit_alter_drugrequest_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact_info',
            new_name='file_no',
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
