# Generated by Django 4.2.7 on 2025-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_contact_info_patient_file_no_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserecord',
            name='date_issued',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispenserecord',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
