# Generated by Django 4.2.7 on 2024-08-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_unitstore_unitissuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitissuerecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitissue_category', to='store.category'),
        ),
    ]
