# Generated by Django 4.2.7 on 2024-08-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_unitissuerecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitissuerecord',
            name='date_issued',
            field=models.DateField(null=True),
        ),
    ]
