# Generated by Django 4.2.7 on 2025-01-27 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_dispenserecord_date_issued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={},
        ),
        migrations.AlterField(
            model_name='drug',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='PACK SIZE'),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_locker', to='store.dispensarylocker'),
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
