# Generated by Django 4.2.7 on 2024-08-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_unitissuerecord_date_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dispensary Locker', max_length=100)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_locker', to='store.unit')),
            ],
        ),
        migrations.AddField(
            model_name='unitissuerecord',
            name='issued_to_locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.dispensarylocker'),
        ),
        migrations.CreateModel(
            name='LockerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.drug')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.dispensarylocker')),
            ],
            options={
                'unique_together': {('locker', 'drug')},
            },
        ),
    ]
