# Generated by Django 4.2.7 on 2025-01-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_drug_options_alter_drug_pack_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_unit', to='store.dispensarylocker'),
        ),
    ]
