# Generated by Django 4.2.7 on 2024-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_dispensarylocker_unitissuerecord_issued_to_locker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockerinventory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
