# Generated by Django 4.2.7 on 2024-08-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_lockerinventory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
