# Generated by Django 4.2.7 on 2024-08-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_drug_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='entered_expiry_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
