# Generated by Django 5.0.1 on 2025-02-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_dispenserecord_date_issued_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='device_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
