# Generated by Django 4.2.7 on 2024-08-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_dispenserecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispenserecord',
            old_name='issued_by',
            new_name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='dispenserecord',
            name='date_issued',
        ),
    ]
