# Generated by Django 4.2.7 on 2024-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_issued_by_dispenserecord_dispensed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unitissuerecord',
            name='date_issued',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
