# Generated by Django 4.2.7 on 2024-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_record_date_issued_alter_restock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restock',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
