# Generated by Django 4.2.7 on 2024-08-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_restock_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='dispense_date',
            field=models.DateField(auto_now=True),
        ),
    ]
