# Generated by Django 4.2.7 on 2024-08-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_dispenserecord_dispense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserecord',
            name='dispense_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispenserecord',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
