# Generated by Django 4.2.7 on 2024-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_dispenserecord_dispense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
