# Generated by Django 4.2.7 on 2024-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_record_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitissuerecord',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unitissuerecord',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
