# Generated by Django 4.2.7 on 2024-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_unitissuerecord_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED'),
        ),
    ]
