# Generated by Django 4.2.7 on 2024-08-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_drug_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
