# Generated by Django 4.2.7 on 2024-08-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_record_date_issued_alter_record_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='restock',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
