# Generated by Django 4.2.7 on 2024-09-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_record_date_issued_alter_restock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
