# Generated by Django 4.2.7 on 2024-09-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0029_alter_restock_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_category', to='store.category')),
                ('drug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.drug')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_returning', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'returned drugs record',
            },
        ),
    ]
