# Generated by Django 4.2.7 on 2024-09-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_box_unitissuerecord_moved_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneddrugs',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_drugs', to='store.unit'),
        ),
        migrations.AlterField(
            model_name='returneddrugs',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
