# Generated by Django 4.2.7 on 2024-09-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_returneddrugs_unit_alter_returneddrugs_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
