# Generated by Django 4.2.7 on 2024-09-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_record_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneddrugs',
            name='patient_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitissuerecord',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
