# Generated by Django 4.2.7 on 2024-12-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_returneddrugs_patient_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, choices=[('expiry box', 'expiry box'), ('damaged box', 'damaged box'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
