# Generated by Django 4.2.7 on 2024-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_box_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, choices=[('expiry', 'expiry'), ('damage', 'damage'), ('other', 'other')], max_length=200, null=True),
        ),
    ]
