# Generated by Django 5.0.4 on 2024-12-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_box_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='balance_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
