# Generated by Django 4.2.7 on 2024-12-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='browser_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
