# Generated by Django 4.2.7 on 2024-12-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_loginactivity_browser_loginactivity_browser_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginactivity',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='device',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='is_mobile',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='is_pc',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='is_tablet',
        ),
        migrations.RemoveField(
            model_name='loginactivity',
            name='os_version',
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='device_type',
            field=models.CharField(default='pc', max_length=50),
        ),
    ]
