# Generated by Django 4.2.7 on 2024-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_loginactivity_browser_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginactivity',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
