# Generated by Django 4.2.7 on 2024-12-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_loginactivity_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='record',
            name='siv',
        ),
        migrations.RemoveField(
            model_name='record',
            name='srv',
        ),
    ]
