# Generated by Django 4.2.7 on 2025-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_remove_record_invoice_no_remove_record_siv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ANALGESIC', 'Analgesic'), ('ANAESTHETIC', 'Anaesthetic'), ('ANTIBIOTIC', 'Antibiotic'), ('ANTICOAGULANT', 'Anticoagulant'), ('ANTICONVULSANT', 'Anticonvulsant'), ('ANTIDEPRESSANT', 'Antidepressant'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIDIARHEAL', 'Antidiarheal'), ('ANTIEMETIC', 'Antiemetic'), ('ANTIFUNGAL', 'Antifungal'), ('ANTIFIBRINOLYTICS', 'Antifibrinolytics'), ('ANTI_ACNE', 'Anti-Acne'), ('ANTIHISTAMINE', 'Antihistamine'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTI-INFLAMMATORY', 'Anti-inflammatory'), ('ANTINEOPLASTIC', 'Antineoplastic'), ('ANTIPARASITIC', 'Antiparasitic'), ('ANTIPSYCHOTIC', 'Antipsychotic'), ('ANTI-TUBERCULOSIS', 'Anti-Tuberculosis'), ('ANTI-UCLER', 'Anti-ulcer'), ('ANTIVIRAL', 'Antiviral'), ('BRONCHODILATOR', 'Bronchodilator'), ('CARDIOVASCULAR', 'Cardiovascular'), ('CNS_STIMULANT', 'CNS Stimulant'), ('CORTICOSTEROID', 'Corticosteroid'), ('CONSUMABLES', 'Consumables'), ('DERMATOLOGICAL', 'Dermatological'), ('DIURETIC', 'Diuretic'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('HORMONE', 'Hormone'), ('IMMUNOSUPPRESSANT', 'Immunosuppressant'), ('LIPID_LOWERING', 'Lipid-lowering'), ('MUSCLE_RELAXANT', 'Muscle Relaxant'), ('NSAID', 'NSAID'), ('OPIOID', 'Opioid'), ('OPHTHALMIC', 'Ophthalmic'), ('PSYCHOTROPIC', 'Psychotropic'), ('SEDATIVES_HYPNOTIC', 'Sedatives/Hypnotic'), ('THYROID_PREPARATION', 'Thyroid Preparation'), ('VACCINE', 'Vaccine'), ('VITAMINS_MINERAL', 'Vitamins and Mineral'), ('OTHER', 'Other')], max_length=200, verbose_name='CLASS OF DRUG'),
        ),
    ]
