# Generated by Django 4.2.7 on 2025-01-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='pack_size',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='PACK SIZE'),
        ),
    ]
