# Generated by Django 4.2.7 on 2025-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_drug_pack_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='pack_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='PACK SIZE'),
        ),
    ]
