# Generated by Django 4.2.7 on 2025-01-05 00:05

from django.db import migrations
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_drug_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='code',
            field=store.models.SerialNumberField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
