# Generated by Django 4.2.7 on 2025-01-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_drug_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='code',
        ),
    ]
