# Generated by Django 4.2.7 on 2025-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_drug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='date_issued',
            field=models.DateField(null=True),
        ),
    ]
